# --- auto-generated scorers start ---
scorers: dict = {
    'sa_score': {
        'function_name': 'score_sa_druglikeness',
        'population_wise': False,
        'description': 'Synthetic Accessibility (SA) druglikeness score (value range: 0.0 to 1.0). SA score estimates how difficult a molecule would be to synthesize, based on fragment contributions and molecular complexity. This metric is crucial for drug discovery as synthetic feasibility directly affects development costs, timelines, and manufacturability. High scores (>0.8) indicate easily synthesizable molecules with simple structures and common fragments, while low scores (<0.3) suggest very challenging synthesis requiring complex multi-step routes or exotic reagents. The scoring is based on the original SA scale (1-10) where lower raw SA values indicate easier synthesis, normalized to 0-1 druglikeness scale where higher normalized scores indicate better synthetic accessibility.',
        'tool_description': 'Calculate Synthetic Accessibility (SA) druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on synthetic accessibility:\n- Score = 1.0: SA ≤ 1 (easily synthesizable molecules)\n- Score = 0.0: SA ≥ 10 (very difficult to synthesize)\n- Score = linear interpolation: SA between 1-10\n\nLower SA scores indicate easier synthesis and are preferred for drug development.\nHigher normalized scores indicate more synthetically accessible molecules.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'deepdl_druglikeness': {
        'function_name': 'score_deepdl_druglikeness',
        'population_wise': False,
        'description': 'DeepDL druglikeness score (value range: 0.0 to 1.0). This is an unsupervised deep learning model trained on the distribution of real approved drugs to capture complex, non-linear drug-like patterns that traditional rule-based filters might miss. The model learns latent representations of drug-like chemical space from marketed pharmaceuticals. High scores (>0.7) indicate strong similarity to approved drugs with optimal drug-like properties, while low scores (<0.3) suggest non-drug-like molecules that deviate significantly from known pharmaceutical space. This scorer complements rule-based approaches by capturing subtle drug-like features and provides a data-driven assessment of overall druglikeness.',
        'tool_description': "Score molecules using DeepDL model; normalize 0-100 → 0-1.\n\nRequires package providing `druglikeness.deepdl.DeepDL`.\nModel is loaded lazily on first use with pretrained 'extended' on CPU.\nReturns None for invalid SMILES or if model unavailable.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'solubility_score': {
        'function_name': 'score_solubility_druglikeness',
        'population_wise': False,
        'description': 'Aqueous solubility druglikeness score (value range: 0.0 to 1.0). Solubility measures how well a compound dissolves in water, which is critical for oral bioavailability, intravenous formulation, and overall pharmacokinetics. Poor solubility is a major cause of drug development failures and limits dosing options. High scores (>0.8) indicate excellent predicted solubility (LogP <2) suitable for various formulations and administration routes, while low scores (<0.3) suggest poor solubility (LogP >4) that may require specialized formulation techniques or limit bioavailability. This score uses LogP as a validated proxy for aqueous solubility, as lipophilic compounds generally have reduced water solubility.',
        'tool_description': 'Calculate solubility druglikeness score using LogP as proxy.\n\nReturns normalized scores between 0.0 and 1.0 based on estimated solubility:\n- Score = 1.0: Estimated good solubility (LogP < 2)\n- Score = 0.0: Estimated poor solubility (LogP > 4)\n- Score = linear interpolation: LogP between 2-4\n\nUses LogP as a proxy for solubility since direct solubility calculation requires more complex models.\nLower LogP generally correlates with better aqueous solubility.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'logp_score': {
        'function_name': 'score_logp_druglikeness',
        'population_wise': False,
        'description': "Lipophilicity (LogP) druglikeness score (value range: 0.0 to 1.0). LogP measures the partition coefficient between octanol and water, indicating the balance between lipophilicity and hydrophilicity. This property is fundamental to drug absorption, distribution, metabolism, and excretion (ADMET). Optimal LogP balance ensures adequate membrane permeability while maintaining sufficient solubility. High scores (>0.8) indicate optimal lipophilicity (LogP <2) with good membrane permeability and water solubility balance, while low scores (<0.3) suggest excessive lipophilicity (LogP >4) leading to poor solubility, potential toxicity, and challenging formulation. LogP is a key component of Lipinski's Rule of Five and strongly correlates with oral bioavailability.",
        'tool_description': 'Calculate LogP druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on lipophilicity (LogP):\n- Score = 1.0: LogP < 2 (optimal lipophilicity for drug-like molecules)\n- Score = 0.0: LogP > 3 (too lipophilic, poor ADMET properties)\n- Score = linear interpolation: LogP between 2-3\n\nLower LogP values indicate better water solubility and permeability balance.\nHigher scores indicate more drug-like lipophilicity.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'mw_score': {
        'function_name': 'score_mw_druglikeness',
        'population_wise': False,
        'description': "Molecular Weight (MW) druglikeness score (value range: 0.0 to 1.0). MW is a fundamental predictor of oral bioavailability and overall drug-like properties, as it affects membrane permeability, metabolic stability, and formulation feasibility. Molecular size directly impacts a compound's ability to cross biological membranes and reach target sites. High scores (>0.8) indicate optimal molecular size (MW ≤400 Da) associated with excellent oral bioavailability and drug-like properties, while low scores (<0.3) suggest large molecules (MW >500 Da) that violate Lipinski's Rule of Five and typically exhibit poor absorption, distribution, and bioavailability. Smaller molecules generally have better ADMET profiles and are easier to formulate.",
        'tool_description': "Calculate molecular weight druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on molecular weight:\n- Score = 1.0: MW ≤ 400 Da (optimal size for oral bioavailability)\n- Score = 0.0: MW > 500 Da (violates Lipinski's Rule of Five)\n- Score = linear interpolation: MW between 400-500 Da\n\nLower molecular weights are generally associated with better ADMET properties.\nHigher scores indicate more drug-like molecular size.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'psa_score': {
        'function_name': 'score_psa_druglikeness',
        'population_wise': False,
        'description': 'Topological Polar Surface Area (TPSA) druglikeness score (value range: 0.0 to 1.0). TPSA measures the surface area occupied by polar atoms (oxygen and nitrogen with attached hydrogens) and is a validated predictor of membrane permeability, blood-brain barrier penetration, and oral bioavailability. TPSA directly correlates with passive diffusion across biological membranes. High scores (>0.8) indicate optimal polar surface area (TPSA ≤120 Ų) associated with excellent membrane permeability and bioavailability, while low scores (<0.3) suggest excessive polarity (TPSA >140 Ų) leading to poor membrane transport, reduced absorption, and limited tissue distribution. TPSA is particularly important for CNS drugs where blood-brain barrier penetration is crucial.',
        'tool_description': 'Calculate Polar Surface Area (PSA) druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on topological PSA:\n- Score = 1.0: PSA ≤ 120 Ų (optimal for membrane permeability)\n- Score = 0.0: PSA > 140 Ų (poor membrane permeability, BBB penetration)\n- Score = linear interpolation: PSA between 120-140 Ų\n\nLower PSA values correlate with better cell membrane permeability.\nHigher scores indicate more drug-like polar surface area.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'rotatable_bonds_score': {
        'function_name': 'score_rotatable_bonds_druglikeness',
        'population_wise': False,
        'description': 'Rotatable Bonds druglikeness score (value range: 0.0 to 1.0). Rotatable bonds measure molecular flexibility and conformational freedom, which affects both target binding affinity and pharmacokinetic properties. Excessive flexibility incurs entropy penalties upon binding and can reduce oral bioavailability. High scores (>0.8) indicate optimal molecular rigidity (≤7 rotatable bonds) associated with strong target binding due to reduced entropy loss and good oral bioavailability, while low scores (<0.3) suggest excessive flexibility (>10 rotatable bonds) leading to weak binding affinity, poor selectivity, and challenging pharmacokinetics. Moderate flexibility is preferred to maintain binding specificity while allowing necessary conformational adjustments.',
        'tool_description': 'Calculate rotatable bonds druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on molecular flexibility:\n- Score = 1.0: ≤ 7 rotatable bonds (optimal flexibility for binding)\n- Score = 0.0: > 10 rotatable bonds (too flexible, entropy penalty)\n- Score = linear interpolation: 7-10 rotatable bonds\n\nFewer rotatable bonds indicate better binding affinity due to lower entropy loss.\nHigher scores indicate more drug-like molecular flexibility.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'fsp3_score': {
        'function_name': 'score_fsp3_druglikeness',
        'population_wise': False,
        'description': "Fraction of sp3 carbons (FSP3) druglikeness score (value range: 0.0 to 1.0). FSP3 measures molecular complexity and three-dimensional character, representing the fraction of carbon atoms with tetrahedral geometry. This metric is crucial for escaping the 'flatland' of aromatic compounds that dominate many chemical libraries. Higher sp3 content provides molecular diversity, improved target selectivity, and better ADMET properties. High scores (>0.8) indicate excellent 3D character (FSP3 >0.3) associated with enhanced selectivity, reduced off-target effects, and improved drug-like properties, while low scores (<0.3) suggest overly flat, aromatic structures (FSP3 <0.2) that may suffer from poor selectivity, increased toxicity, and limited chemical space exploration. Three-dimensional molecules often have superior pharmacological profiles.",
        'tool_description': 'Calculate fraction of sp3 carbons (FSP3) druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on molecular complexity:\n- Score = 1.0: FSP3 > 0.3 (optimal 3D character, escape from flatland)\n- Score = 0.0: FSP3 < 0.2 (too flat/aromatic, poor selectivity)\n- Score = linear interpolation: FSP3 between 0.2-0.3\n\nHigher FSP3 values indicate more 3D character and better drug-like properties.\nMolecules with higher sp3 content tend to have better selectivity and ADMET.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'rings_score': {
        'function_name': 'score_rings_druglikeness',
        'population_wise': False,
        'description': 'Number of rings druglikeness score (value range: 0.0 to 1.0). Ring count affects molecular complexity, structural rigidity, and synthetic accessibility. Ring systems provide structural frameworks for target binding while influencing synthetic feasibility and optimization potential. High scores (>0.8) indicate simple ring systems (<1 ring) that are easily synthesizable, readily optimizable, and have favorable ADMET properties, while low scores (<0.3) suggest complex polycyclic systems (>2 rings) that may be synthetically challenging, difficult to optimize, and prone to poor drug-like properties. Moderate ring content balances structural diversity needed for target binding with synthetic and optimization feasibility required for drug development.',
        'tool_description': 'Calculate number of rings druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on ring count:\n- Score = 1.0: < 1 ring (simple, acyclic structures)\n- Score = 0.0: > 2 rings (complex polycyclic systems)\n- Score = linear interpolation: 1-2 rings\n\nFewer rings generally correlate with easier synthesis and optimization.\nHigher scores indicate more drug-like ring complexity.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'hbd_score': {
        'function_name': 'score_hbd_druglikeness',
        'population_wise': False,
        'description': "Hydrogen Bond Donors (HBD) druglikeness score (value range: 0.0 to 1.0). HBD count measures the number of hydrogen atoms attached to electronegative atoms (N, O) that can donate hydrogen bonds, affecting membrane permeability and oral bioavailability per Lipinski's Rule of Five. HBDs enable specific interactions with biological targets but can impede membrane transport. High scores (>0.8) indicate optimal HBD count (<3) associated with excellent membrane permeability and oral bioavailability while maintaining target binding capability, while low scores (<0.3) suggest excessive hydrogen bonding capacity (>5 HBDs) leading to poor membrane transport, reduced absorption, and potential formulation challenges. Balance between target interaction and permeability is crucial for drug success.",
        'tool_description': 'Calculate hydrogen bond donors (HBD) druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on HBD count:\n- Score = 1.0: < 3 HBD (optimal for membrane permeability)\n- Score = 0.0: > 5 HBD (poor membrane permeability)\n- Score = linear interpolation: 3-5 HBD\n\nFewer HBDs generally correlate with better membrane permeability.\nHigher scores indicate more drug-like hydrogen bonding capacity.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'hba_score': {
        'function_name': 'score_hba_druglikeness',
        'population_wise': False,
        'description': "Hydrogen Bond Acceptors (HBA) druglikeness score (value range: 0.0 to 1.0). HBA count measures nitrogen and oxygen atoms that can accept hydrogen bonds, significantly affecting membrane permeability and bioavailability according to Lipinski's Rule of Five. HBAs facilitate target binding through specific interactions but can hinder passive diffusion across membranes. High scores (>0.8) indicate optimal HBA count (<5) associated with good membrane permeability and oral bioavailability while providing sufficient binding interactions, while low scores (<0.3) suggest excessive hydrogen bonding capacity (>10 HBAs) leading to poor membrane transport, reduced tissue distribution, and potential bioavailability issues. Proper balance between molecular recognition and membrane permeability is essential for drug efficacy.",
        'tool_description': 'Calculate hydrogen bond acceptors (HBA) druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on HBA count:\n- Score = 1.0: < 5 HBA (optimal for membrane permeability)\n- Score = 0.0: > 10 HBA (poor membrane permeability)\n- Score = linear interpolation: 5-10 HBA\n\nFewer HBAs generally correlate with better membrane permeability.\nHigher scores indicate more drug-like hydrogen bonding capacity.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'heavy_atoms_score': {
        'function_name': 'score_heavy_atoms_druglikeness',
        'population_wise': False,
        'description': 'Heavy atoms count druglikeness score (value range: 0.0 to 1.0). Heavy atoms (all non-hydrogen atoms) determine overall molecular size, complexity, and drug-like character. This count directly correlates with molecular weight and affects all ADMET properties including absorption, distribution, metabolism, and excretion. High scores (>0.8) indicate optimal molecular size (<50 heavy atoms) associated with excellent drug-like properties, good bioavailability, and manageable synthetic complexity, while low scores (<0.3) suggest large, complex molecules (>70 heavy atoms) that typically exhibit poor ADMET properties, challenging synthesis, difficult optimization, and increased development risks. Smaller molecules generally have superior pharmacological profiles and development success rates.',
        'tool_description': 'Calculate heavy atoms druglikeness score.\n\nReturns normalized scores between 0.0 and 1.0 based on heavy atom count:\n- Score = 1.0: < 50 heavy atoms (optimal molecular size)\n- Score = 0.0: > 70 heavy atoms (too large, complex)\n- Score = linear interpolation: 50-70 heavy atoms\n\nFewer heavy atoms generally correlate with better drug-like properties.\nHigher scores indicate more appropriate molecular size.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'qed': {
        'function_name': 'score_qed',
        'population_wise': False,
        'description': 'Quantitative Estimate of Drug-likeness (QED) score (value range: 0.0 to 1.0). QED is a validated, comprehensive metric that combines eight key molecular descriptors (molecular weight, LogP, hydrogen bond donors, hydrogen bond acceptors, topological polar surface area, rotatable bonds, aromatic rings, and structural alerts) weighted by their statistical importance in approved oral drugs. This benchmark assessment is calibrated on marketed pharmaceuticals to provide the most accurate druglikeness evaluation. High scores (>0.7) indicate excellent drug-like properties with strong similarity to successful marketed drugs across multiple physicochemical dimensions, while low scores (<0.3) suggest poor overall drug-likeness with multiple violations of optimal ranges. QED serves as the gold standard for druglikeness assessment, integrating multiple critical factors into a single, validated score.',
        'tool_description': "Calculate Quantitative Estimate of Drug-likeness (QED).\n\nReturns normalized scores between 0.0 and 1.0 using RDKit's QED implementation:\n- Score = 1.0: Excellent drug-like properties (similar to approved drugs)\n- Score = 0.0: Poor drug-like properties \n- Score = continuous: Weighted combination of 8 molecular descriptors\n\nQED considers molecular weight, LogP, HBD, HBA, PSA, rotatable bonds,\naromatic rings, and alerts. It's calibrated on approved oral drugs.\n\nHigher scores indicate greater similarity to known oral drugs.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'pains_filter': {
        'function_name': 'score_pains',
        'population_wise': False,
        'description': 'Pan-Assay Interference Compounds (PAINS) filter score (value range: 0.0 or 1.0). PAINS are structural motifs that frequently show activity in biochemical assays through non-specific mechanisms rather than genuine target binding, leading to false positives in drug discovery. These compounds interfere with assays through mechanisms like aggregation, fluorescence, reactivity, or redox cycling. A score of 1.0 indicates the molecule contains no PAINS alerts (classes A, B, or C) and is suitable for further development, while a score of 0.0 indicates the presence of one or more PAINS motifs that may cause assay interference and should be avoided in drug discovery campaigns. PAINS filtering is essential for focusing resources on compounds with genuine biological activity.',
        'tool_description': 'Calculate Pan-Assay Interference Compounds (PAINS) filter score.\n\nReturns binary scores between 0.0 and 1.0 based on PAINS structural alerts:\n- Score = 1.0: No PAINS alerts detected (clean compound, suitable for screening)\n- Score = 0.0: PAINS alerts detected (problematic structure, avoid in drug discovery)\n\nUses combined PAINS A/B/C filter catalogs to detect promiscuous compounds that\nfrequently appear as false positives in biochemical assays. PAINS compounds\ninterfere with assays through non-specific mechanisms rather than genuine\nbiological activity and should be filtered out early in drug discovery.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'brenk_filter': {
        'function_name': 'score_brenk',
        'population_wise': False,
        'description': 'Brenk structural alerts filter score (value range: 0.0, 0.5, or 1.0). Brenk alerts identify structural motifs associated with toxicity, reactivity, or other undesirable properties that can lead to drug development failures. These alerts help flag potentially problematic compounds early in the discovery process. A score of 1.0 indicates no structural alerts and excellent safety profile potential, a score of 0.5 indicates exactly one alert requiring careful evaluation and potential optimization, while a score of 0.0 indicates multiple alerts (≥2) suggesting significant safety or developability concerns that typically warrant compound deprioritization. Brenk filtering helps prioritize safer compounds and avoid costly late-stage failures due to toxicity or reactivity issues.',
        'tool_description': 'Calculate Brenk structural alerts filter score.\n\nReturns scores between 0.0 and 1.0 based on Brenk structural alerts:\n- Score = 1.0: No Brenk alerts detected (clean compound, no known liabilities)\n- Score = 0.5: Exactly one Brenk alert detected (moderate concern, review required)\n- Score = 0.0: Multiple Brenk alerts detected (high risk, avoid in drug development)\n\nBrenk filters identify structural motifs associated with toxicity, reactivity,\nmetabolism issues, and other undesirable ADMET properties. These alerts help\nflag compounds with potential safety or pharmacokinetic liabilities that\nshould be deprioritized or avoided in drug discovery campaigns.\n\nArgs:\n    samples: List of input samples, where each sample is a SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
}
# --- auto-generated scorers end ---
