# --- auto-generated scorers start ---
scorers: dict = {
    'dna_hepg2_enhancer_MPRA_expression': {
        'function_name': 'score_hepg2_expression',
        'population_wise': False,
        'description': 'HepG2 MPRA expression score (value range: -∞ to +∞). MPRA (Massively Parallel Reporter Assay) quantifies gene expression driven by DNA sequences using massively parallel sequencing to measure how well different sequences drive reporter gene expression. This score evaluates DNA enhancer sequences based on their predicted expression levels in HepG2 cells (human hepatocellular carcinoma cell line). Higher scores indicate stronger enhancer activity and greater gene expression in liver-like cellular contexts. Lower scores suggest weaker enhancer activity or potential silencing effects. This metric is essential for designing DNA sequences that need to function specifically in hepatic environments or liver-related therapeutic applications.',
        'tool_description': 'Calculate HepG2 MPRA expression score for DNA enhancer sequences.\n\nUses an Enformer-based model to predict expression levels of DNA sequences in HepG2 cells.\nThe model analyzes sequence patterns to predict enhancer activity specific to hepatic cellular contexts.\n\n- Higher scores (> 0): Strong enhancer activity, increased gene expression\n- Lower scores (< 0): Weak enhancer activity or silencing effects\n- Score = None: Invalid DNA sequences or computation errors\n\nThis scoring is particularly valuable for liver-targeted therapeutic applications and \nunderstanding hepatic gene regulation mechanisms.\n   \nArgs:\n    samples: List of input samples, where each sample is a DNA sequence string\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'dna_k562_enhancer_MPRA_expression': {
        'function_name': 'score_k562_expression',
        'population_wise': False,
        'description': 'K562 MPRA expression score (value range: -∞ to +∞). MPRA (Massively Parallel Reporter Assay) quantifies gene expression driven by DNA sequences using massively parallel sequencing to measure how well different sequences drive reporter gene expression. This score evaluates DNA enhancer sequences based on their predicted expression levels in K562 cells (human erythroleukemic cell line). Higher scores indicate stronger enhancer activity and greater gene expression in hematopoietic cellular contexts. Lower scores suggest weaker enhancer activity or potential silencing effects. This metric is crucial for designing DNA sequences that need to function in blood cell lineages or hematological therapeutic applications.',
        'tool_description': 'Calculate K562 MPRA expression score for DNA enhancer sequences.\n\nUses an Enformer-based model to predict expression levels of DNA sequences in K562 cells.\nThe model analyzes sequence patterns to predict enhancer activity specific to erythroleukemic cellular contexts.\n\n- Higher scores (> 0): Strong enhancer activity, increased gene expression\n- Lower scores (< 0): Weak enhancer activity or silencing effects\n- Score = None: Invalid DNA sequences or computation errors\n\nThis scoring is particularly valuable for hematological research and blood-related therapeutic applications\nwhere understanding gene regulation in blood cell lineages is essential.\n   \nArgs:\n    samples: List of input samples, where each sample is a DNA sequence string\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'dna_sknsh_enhancer_MPRA_expression': {
        'function_name': 'score_sknsh_expression',
        'population_wise': False,
        'description': 'SKNSH MPRA expression score (value range: -∞ to +∞). MPRA (Massively Parallel Reporter Assay) quantifies gene expression driven by DNA sequences using massively parallel sequencing to measure how well different sequences drive reporter gene expression. This score evaluates DNA enhancer sequences based on their predicted expression levels in SKNSH cells (human neuroblastoma cell line). Higher scores indicate stronger enhancer activity and greater gene expression in neuronal cellular contexts. Lower scores suggest weaker enhancer activity or potential silencing effects. This metric is essential for designing DNA sequences that need to function in neural tissues or neurological therapeutic applications.',
        'tool_description': 'Calculate SKNSH MPRA expression score for DNA enhancer sequences.\n\nUses an Enformer-based model to predict expression levels of DNA sequences in SKNSH cells.\nThe model analyzes sequence patterns to predict enhancer activity specific to neuroblastoma cellular contexts.\n\n- Higher scores (> 0): Strong enhancer activity, increased gene expression\n- Lower scores (< 0): Weak enhancer activity or silencing effects\n- Score = None: Invalid DNA sequences or computation errors\n\nThis scoring is particularly valuable for neurological research and neural therapeutic applications\nwhere understanding gene regulation in neural cell lineages is critical.\n   \nArgs:\n    samples: List of input samples, where each sample is a DNA sequence string\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
}
# --- auto-generated scorers end ---
