# --- auto-generated scorers start ---
scorers: dict = {
    'drd2_unidock': {
        'function_name': 'score_drd2_unidock',
        'population_wise': False,
        'description': "DRD2 UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to the dopamine D2 receptor (DRD2) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for DRD2 antagonist or agonist development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited therapeutic potential. DRD2 is a key target for antipsychotic drugs and Parkinson's disease therapeutics, making this score valuable for CNS drug discovery.",
        'tool_description': 'Calculate the normalized docking score for DRD2 using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to the dopamine D2 receptor.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'gsk3b_unidock': {
        'function_name': 'score_gsk3b_unidock',
        'population_wise': False,
        'description': 'GSK3B UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to glycogen synthase kinase-3 beta (GSK3B) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for GSK3B inhibitor development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited kinase inhibition potential. GSK3B is a critical target for diabetes, cancer, and neurological disorders, making this score important for multi-therapeutic drug discovery.',
        'tool_description': 'Calculate the normalized docking score for GSK3B using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to glycogen synthase kinase-3 beta.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'jnk3_unidock': {
        'function_name': 'score_jnk3_unidock',
        'population_wise': False,
        'description': 'JNK3 UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to c-Jun N-terminal kinase 3 (JNK3) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for JNK3 inhibitor development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited therapeutic potential. JNK3 is a key target for neurodegenerative diseases and inflammatory conditions, making this score valuable for neuroprotective drug discovery.',
        'tool_description': 'Calculate the normalized docking score for JNK3 using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to c-Jun N-terminal kinase 3.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'brd4_unidock': {
        'function_name': 'score_brd4_unidock',
        'population_wise': False,
        'description': 'BRD4 UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to bromodomain-containing protein 4 (BRD4) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for BRD4 inhibitor development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited epigenetic modulation potential. BRD4 is a crucial target for cancer therapy and inflammatory diseases, making this score important for epigenetic drug discovery.',
        'tool_description': 'Calculate the normalized docking score for BRD4 using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to bromodomain-containing protein 4.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'mpro_unidock': {
        'function_name': 'score_mpro_unidock',
        'population_wise': False,
        'description': 'MPRO UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to SARS-CoV-2 main protease (MPRO) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (≥0.6) indicate good predicted binding affinity (≤-9.0 kcal/mol) suitable for COVID-19 antiviral development, while low scores (≤0.5) suggest insufficient binding (<-7.5 kcal/mol) with limited protease inhibition potential. MPRO is an essential target for coronavirus therapeutics, making this score critical for antiviral drug discovery.',
        'tool_description': 'Calculate the normalized docking score for MPRO using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to SARS-CoV-2 main protease.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\nAlso computes protein-ligand interaction scores for use by interaction-specific scorers.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'mpro_his161_a': {
        'function_name': 'score_mpro_his161_a',
        'population_wise': False,
        'description': 'MPRO HIS161/A hydrogen bond interaction score (value range: 0.0 or 1.0). This binary score indicates whether the docked molecule forms a hydrogen bond with the critical HIS161 residue in chain A of the SARS-CoV-2 main protease active site. The score is computed using PLIP (Protein-Ligand Interaction Profiler) analysis of the docked pose. A score of 1.0 indicates the presence of a hydrogen bond interaction with HIS161/A, which is essential for MPRO inhibition, while a score of 0.0 indicates no such interaction. HIS161 is part of the catalytic dyad and hydrogen bonding with this residue is crucial for effective protease inhibition and antiviral activity. This interaction is very common in known MPRO binders and represents a key pharmacophore feature.',
        'tool_description': "Calculate MPRO HIS161/A hydrogen bond interaction score.\n\nAnalyzes docked poses using PLIP to identify hydrogen bond interactions with HIS161 residue.\nReturns binary scores indicating presence (1.0) or absence (0.0) of this critical interaction.\nIf MPRO docking hasn't been performed yet, it will be computed automatically.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'mpro_glu164_a': {
        'function_name': 'score_mpro_glu164_a',
        'population_wise': False,
        'description': 'MPRO GLU164/A hydrogen bond interaction score (value range: 0.0 or 1.0). This binary score indicates whether the docked molecule forms a hydrogen bond with the GLU164 residue in chain A of the SARS-CoV-2 main protease active site. The score is computed using PLIP (Protein-Ligand Interaction Profiler) analysis of the docked pose. A score of 1.0 indicates the presence of a hydrogen bond interaction with GLU164/A, which stabilizes inhibitor binding in the active site, while a score of 0.0 indicates no such interaction. GLU164 is located in the S1 binding pocket and interactions with this residue enhance binding selectivity and inhibitor potency against MPRO. This interaction is very common in known MPRO binders and is considered a critical binding motif.',
        'tool_description': "Calculate MPRO GLU164/A hydrogen bond interaction score.\n\nAnalyzes docked poses using PLIP to identify hydrogen bond interactions with GLU164 residue.\nReturns binary scores indicating presence (1.0) or absence (0.0) of this critical interaction.\nIf MPRO docking hasn't been performed yet, it will be computed automatically.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'mpro_his39_a': {
        'function_name': 'score_mpro_his39_a',
        'population_wise': False,
        'description': 'MPRO HIS39/A pi-stacking interaction score (value range: 0.0 or 1.0). This binary score indicates whether the docked molecule forms a pi-stacking interaction with the HIS39 residue in chain A of the SARS-CoV-2 main protease active site. The score is computed using PLIP (Protein-Ligand Interaction Profiler) analysis of the docked pose. A score of 1.0 indicates the presence of a pi-stacking interaction with HIS39/A, which provides additional binding affinity and selectivity, while a score of 0.0 indicates no such interaction. HIS39 is positioned in the active site and pi-stacking interactions with aromatic inhibitors can significantly enhance binding affinity and contribute to antiviral potency.',
        'tool_description': "Calculate MPRO HIS39/A pi-stacking interaction score.\n\nAnalyzes docked poses using PLIP to identify pi-stacking interactions with HIS39 residue.\nReturns binary scores indicating presence (1.0) or absence (0.0) of this critical interaction.\nIf MPRO docking hasn't been performed yet, it will be computed automatically.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations",
    },
    'ampcclean_unidock': {
        'function_name': 'score_ampcclean_unidock',
        'population_wise': False,
        'description': 'AMPC UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to AmpC beta-lactamase calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for beta-lactamase inhibitor development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited antibiotic resistance reversal potential. AmpC is a key target for combating antibiotic resistance, making this score valuable for developing adjuvant therapies to restore beta-lactam antibiotic efficacy.',
        'tool_description': 'Calculate the normalized docking score for AMPC using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to AmpC beta-lactamase.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
    'muopioidclean_unidock': {
        'function_name': 'score_muopioidclean_unidock',
        'population_wise': False,
        'description': 'Mu-opioid receptor UniDock binding affinity score (value range: 0.0 to 1.0). This score represents the normalized binding affinity to the mu-opioid receptor (MOR) calculated using UniDock molecular docking. The raw UniDock scores (in kcal/mol, where more negative values indicate stronger binding) are normalized by dividing by -15.0 and clipping to 0-1 range. High scores (>0.7) indicate strong predicted binding affinity (≤-10.5 kcal/mol) suitable for opioid analgesic development, while low scores (<0.3) suggest weak binding (>-4.5 kcal/mol) with limited pain management potential. The mu-opioid receptor is the primary target for opioid analgesics, making this score important for pain management drug discovery while considering addiction potential.',
        'tool_description': 'Calculate the normalized docking score for mu-opioid receptor using UniDock.\n\nUses UniDock molecular docking to predict binding affinity to the mu-opioid receptor.\nRaw scores in kcal/mol are normalized to 0-1 range where higher values indicate stronger binding.\n\nArgs:\n    samples: List of input samples, where each sample is the SMILES string of a molecule\n\nReturns:\n    List of float scores, each calculated for each sample; scores can be None for invalid samples or invalid computations',
    },
}
# --- auto-generated scorers end ---
