"""
Genetic operators for molecular optimization.

Provides strategy pattern for crossover and mutation operations.
"""

from abc import ABC, abstractmethod
from typing import Callable, List, Optional

from scileo_agent.core.data_models import Candidate, Objective
from modules.small_molecule_drug_design.utils.mutation_ops import mutate_smiles


class GeneticOperator(ABC):
    """Abstract base class for genetic operations."""

    @abstractmethod
    def apply(self, *args, **kwargs) -> Candidate:
        """
        Apply the genetic operation.

        Returns:
            New candidate generated by the operation
        """
        pass


class LLMCrossover(GeneticOperator):
    """LLM-based crossover operator."""

    def __init__(self, llm_handler):
        """
        Initialize LLM crossover.

        Args:
            llm_handler: MolecularLLMHandler instance
        """
        self.llm_handler = llm_handler

    def apply(
        self,
        parent_a: Candidate,
        parent_b: Candidate,
        objectives: List[Objective],
        objectives_weights: List[float],
        return_artifacts: bool = False,
    ):
        """
        Perform LLM-guided crossover.

        Args:
            parent_a: First parent
            parent_b: Second parent
            objectives: Optimization objectives
            objectives_weights: Objective weights
            return_artifacts: Whether to return prompt/response

        Returns:
            Offspring candidate (and optionally artifacts)
        """
        parents = [parent_a, parent_b]
        return self.llm_handler.request_crossover(
            parents, objectives, objectives_weights, return_artifacts=return_artifacts
        )


class RDKitMutation(GeneticOperator):
    """RDKit-based chemical mutation operator."""

    def __init__(self, mutation_rate: float = 1.0, sanitize_fn: Optional[Callable] = None):
        """
        Initialize RDKit mutation.

        Args:
            mutation_rate: Probability of applying mutation
            sanitize_fn: Function to sanitize SMILES
        """
        self.mutation_rate = mutation_rate
        self.sanitize_fn = sanitize_fn or (lambda x: str(x).strip())

    def apply(
        self,
        candidate: Candidate,
        objectives: List[Objective] = None,
        return_artifacts: bool = False,
    ):
        """
        Perform RDKit-based mutation.

        Args:
            candidate: Candidate to mutate
            objectives: Unused (for interface compatibility)
            return_artifacts: Whether to return artifacts

        Returns:
            Mutated candidate (and optionally artifacts)
        """
        mutated_smiles = mutate_smiles(candidate.representation, self.mutation_rate)
        mutant = Candidate(representation=self.sanitize_fn(mutated_smiles))

        if return_artifacts:
            return mutant, "NON_LLM_MUTATION", {"content": "non-llm"}
        return mutant


class LLMMutation(GeneticOperator):
    """LLM-based mutation operator."""

    def __init__(self, llm_handler):
        """
        Initialize LLM mutation.

        Args:
            llm_handler: MolecularLLMHandler instance
        """
        self.llm_handler = llm_handler

    def apply(
        self,
        candidate: Candidate,
        objectives: List[Objective],
        objectives_weights: List[float],
        return_artifacts: bool = False,
    ):
        """
        Perform LLM-guided mutation.

        Args:
            candidate: Candidate to mutate
            objectives: Optimization objectives
            objectives_weights: Objective weights
            return_artifacts: Whether to return prompt/response

        Returns:
            Mutated candidate (and optionally artifacts)
        """
        return self.llm_handler.request_mutation(
            candidate, objectives, objectives_weights, return_artifacts=return_artifacts
        )


class HybridMutation(GeneticOperator):
    """Hybrid mutation combining RDKit and LLM approaches."""

    def __init__(
        self,
        llm_handler,
        llm_probability: float = 0.5,
        rdkit_mutation_rate: float = 1.0,
        sanitize_fn: Optional[Callable] = None,
    ):
        """
        Initialize hybrid mutation.

        Args:
            llm_handler: MolecularLLMHandler instance
            llm_probability: Probability of using LLM vs RDKit
            rdkit_mutation_rate: Mutation rate for RDKit
            sanitize_fn: Function to sanitize SMILES
        """
        self.llm_mutation = LLMMutation(llm_handler)
        self.rdkit_mutation = RDKitMutation(rdkit_mutation_rate, sanitize_fn)
        self.llm_probability = llm_probability

    def apply(
        self,
        candidate: Candidate,
        objectives: List[Objective],
        objectives_weights: List[float],
        return_artifacts: bool = False,
    ):
        """
        Perform hybrid mutation (choose LLM or RDKit randomly).

        Args:
            candidate: Candidate to mutate
            objectives: Optimization objectives
            objectives_weights: Objective weights
            return_artifacts: Whether to return artifacts

        Returns:
            Mutated candidate (and optionally artifacts)
        """
        import random

        if random.random() < self.llm_probability:
            return self.llm_mutation.apply(
                candidate, objectives, objectives_weights, return_artifacts
            )
        else:
            return self.rdkit_mutation.apply(candidate, objectives, return_artifacts)


def create_crossover_operator(
    mode: str, llm_handler=None, **kwargs
) -> GeneticOperator:
    """
    Factory function for creating crossover operators.

    Args:
        mode: "llm" for LLM-based crossover
        llm_handler: MolecularLLMHandler (required for LLM mode)
        **kwargs: Additional arguments

    Returns:
        Crossover operator instance
    """
    if mode == "llm":
        if llm_handler is None:
            raise ValueError("llm_handler required for LLM crossover")
        return LLMCrossover(llm_handler)
    else:
        raise ValueError(f"Unknown crossover mode: {mode}")


def create_mutation_operator(
    mode: str,
    llm_handler=None,
    mutation_rate: float = 1.0,
    sanitize_fn: Optional[Callable] = None,
    **kwargs,
) -> GeneticOperator:
    """
    Factory function for creating mutation operators.

    Args:
        mode: "llm", "non_llm", or "hybrid"
        llm_handler: MolecularLLMHandler (required for LLM/hybrid modes)
        mutation_rate: Mutation rate for RDKit
        sanitize_fn: Function to sanitize SMILES
        **kwargs: Additional arguments (e.g., llm_probability for hybrid)

    Returns:
        Mutation operator instance
    """
    if mode == "llm":
        if llm_handler is None:
            raise ValueError("llm_handler required for LLM mutation")
        return LLMMutation(llm_handler)
    elif mode == "non_llm":
        return RDKitMutation(mutation_rate, sanitize_fn)
    elif mode == "hybrid":
        if llm_handler is None:
            raise ValueError("llm_handler required for hybrid mutation")
        return HybridMutation(
            llm_handler,
            llm_probability=kwargs.get("llm_probability", 0.5),
            rdkit_mutation_rate=mutation_rate,
            sanitize_fn=sanitize_fn,
        )
    else:
        raise ValueError(f"Unknown mutation mode: {mode}")
